<a href="https://colab.research.google.com/github/vjbarayuga/Week1-Python-for-Data-Science-CodingDojo/blob/main/NumpyPracticeNew.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 1 (Intro to Numpy Arrays)

In [1]:
price = [2, 1, 10]
type(price)

list

In [2]:
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

In [3]:
import numpy as np

In [4]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [5]:
price_array * quantity_sold_array

array([34, 40, 10])

In [6]:
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


In [7]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [8]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [9]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


# Numpy 2 (Bakery Numpy Exercise)


In [10]:
quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
print(quantity_sold_array)

[17 40  1  2  3 16  5]


In [11]:
# brownie, cookie, cake, pie, fuge, cupcake, banana bread
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


In [12]:
full_price = price_array * quantity_sold_array
print(full_price)

[34.  39.  12.  14.  13.5 48.  20. ]


In [13]:
# brownie, cookie, cake, pie, fuge, cupcake, banana bread
quantity_leftover = np.array([0., 0., 2., 1., 6., 0., 2.])
print(quantity_leftover)

[0. 0. 2. 1. 6. 0. 2.]


In [14]:
#clearance_price = np.array([0., 0., 6., 3.5, 2.25, 0., 2.0])
#print(clearance_price)

clearance_price = (price_array * .5)
print(clearance_price)

[1.   0.5  6.   3.5  2.25 1.5  2.  ]


In [15]:
clearance = quantity_leftover * clearance_price
print(clearance)


[ 0.   0.  12.   3.5 13.5  0.   4. ]


In [16]:
total_money_collection = full_price + clearance
print(total_money_collection)

[34.  39.  24.  17.5 27.  48.  24. ]


In [17]:
print((total_money_collection[0])+(total_money_collection[1])+(total_money_collection[2])+(total_money_collection[3])+(total_money_collection[4])+(total_money_collection[5])+(total_money_collection[6]))



213.5


In [18]:
print(
    (total_money_collection[0]) + 
    (total_money_collection[1]) + 
    (total_money_collection[2]) + 
    (total_money_collection[3]) + 
    (total_money_collection[4]) + 
    (total_money_collection[5]) + 
    (total_money_collection[6])
)



213.5


In [19]:
print(
    total_money_collection[0] + 
    total_money_collection[1] + 
    total_money_collection[2] + 
    total_money_collection[3] + 
    total_money_collection[4] + 
    total_money_collection[5] + 
    total_money_collection[6]
)

213.5


In [20]:
total = 0
for money in total_money_collection:
    #total += money
    total = total + money

print(total)

213.5


In [21]:
total = sum(total_money_collection)
print(total)

213.5
